services:
  app:
    build: .
    container_name: app.movies-series
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      DB_USER: "example"
      DB_PASSWORD: "example"
      DB_HOST: db
      DB_DATABASE: "example"
      DB_PORT: "5432"
    networks:
      - default
    depends_on:
      - db
  db:
    container_name: db.movies-series
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    networks:
      - default
networks:
  default:
    driver: bridge