version: '3'

services:
  app:
    build: .
    container_name: app.movies-series
    ports:
      - "8091:3000"
    environment:
      DB_USER: ""
      DB_PASSWORD: ""
      DB_HOST: ""
      DB_DATABASE: ""
      DB_PORT: ""
    networks:
      - default
      - interdocker
    restart: unless-stopped

networks:
  default:
    driver: bridge
  interdocker:
    external: true